### ISSUE TITLE
UI - Populate Modify entry window

### ISSUE THREAD

**Issue by Cortesj** [Berea-CS-Courses/capstone-project-Cortesj#29]
I need to create a slave window and populate it with the appropriate input boxes and checks for said boxes so input can be passed on to function for Database modify the entry.

**Comment by mario-nakazawa** [comment]
There needs to a way to check for the input to be correct format. Otherwise you run the risk of corrupting the database with garbage and then it becomes unusable. 
A better strategy would be to limit what the user can type in. When modifying the inventory, it would help if your program gave the user options from which they can select what they want. Maybe you can have a dropdown option for searching for specific things. Then you would need the following process:
1) query the database "SELECT Name from <TABLE>", make sure that all the returned values are unique. 
2) use the returned values to populate a dropdown or maybe checkboxes or something.
3) the user selects and then clicks the button to query the database. If the user does not select anything, nothing happens, but if the user selects an option, the program extracts the value from the dropdown and creates the SQL query with that information.
